name: 'Release Files Action'
description: 'Upload or download assets from given github release'
author: 'Michał Katański'

branding:
  icon: 'archive'
  color: 'orange'

inputs:
  token:
    description: 'GitHub token'
    required: true

  release-tag:
    description: 'Tag releated to release'
    required: true

  file:
    description: 'File to upload'
    required: true

  name:
    description: 'Asset name'
    required: true

  label:
    description: 'Asset label'
    required: false

  content-type:
    description: 'File content type'
    default: 'application/zip'

outputs:
  download-url:
    description: 'Download URL of uploaded asset'
  id:
    description: 'ID of uploaded asset'
  label:
    description: 'Label of uploaded asset'
  name:
    description: 'Name of uploaded asset'

runs:
  using: node20
  main: dist/index.js
