name: 'Release Files Action'
description: 'Upload or download assets from given github release'
author: 'Michał Katański'

branding:
  icon: 'archive'
  color: 'orange'

inputs:
  token:
    description: 'GitHub token'
    type: string
    required: true

  release-tag:
    description: 'Tag releated to release'
    type: string
    required: true

  file-path:
    description: 'File path to upload or download'
    type: string
    required: true

  name:
    description: 'Asset name (default to file-path name)'
    type: string
    required: false

  label:
    description: 'Asset label'
    type: string
    required: false

  content-type:
    description: 'File content type'
    type: string
    default: 'application/zip'
    required: false

  mode:
    description: 'Choose download or upload asset'
    type: string
    default: upload
    required: false

  not-found-behaviour:
    description: "Choose if action should fail or set output when asset is not found"
    type: string
    default: error
    required: false

outputs:
  file-not-found:
    description: ""

runs:
  using: node16
  main: dist/index.js
